# Generated by Django 6.0.6 on 2026-06-17 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('fecha_actividad', models.DateField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('velocidad_viento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
